apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: automate-n8n
spec:
  volumeName: pv-n8n
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
