apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-n8n
  namespace: automate-n8n
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/n8n
  persistentVolumeReclaimPolicy: Retain
