apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: automate-n8n
spec:
  volumeName: pv-postgres              
  storageClassName: ""               
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
